[licenses]
version = 2
confidence-threshold = 0.8
allow = ["Apache-2.0", "MIT", "Zlib", "MPL-2.0", "Unicode-DFS-2016"]

[advisories]
version = 2

[bans]
multiple-versions = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
